version: '3'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    build: ./frontend
    volumes:
      - ./frontend/build:/usr/share/nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
